#
# mingw_0703.yml
#
# input: mingw_0703.zip
# output: mingw_0703.zip
#

name: mingw_0703

on:
#  push:
  schedule:
   - cron: "0 1 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'mingw_0703'
        default: 'mingw_0703'
        required: true

jobs:

  Build:
    #if: env.GITHUB_EVENT_NAME == 'schedulle' || env.GITHUB_EVENT_NAME == 'workflow_dispatch'
    runs-on: windows-latest

    steps:

    - name: load mingw_0703.zip from workflow
      uses: dawidd6/action-download-artifact@v6
      #if: $( { github.event_name = 'schedule' || github.event_name = 'workflow_dispatch' } )
      with:
         workflow: mingw_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/sefazclass

    - name: Save mingw_0703.zip to workflow
      uses: actions/upload-artifact@v4
      with:
         name: mingw_0703
         path: c:\temp\mingw_0703.7z
